import Head from 'next/head'
import { HomeIcon } from '@heroicons/react/outline'
import HeaderItem from '../components/HeaderItem'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind Css Bug Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex flex-row items-center justify-center h-screen">
        <HeaderItem title="Home" Icon={HomeIcon} />
      </main>

    </div>
  )
}
